name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4️⃣ Run script
      - name: Run main script
        run: python "credit card fraud detection_.py"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t credit-card-fraud:latest .
